# Generated by Django 4.2.7 on 2024-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_table',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='user_table',
            name='password2',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
