# Generated by Django 4.2.7 on 2024-07-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_table_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
