# Generated by Django 4.2.7 on 2024-07-30 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_user_table_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('current_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('timestamp', models.IntegerField()),
                ('song_state', models.BooleanField()),
                ('artist', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('track', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listeners', models.ManyToManyField(related_name='listening_sessions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_sessions', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.song')),
            ],
        ),
        migrations.DeleteModel(
            name='user_table',
        ),
        migrations.AddField(
            model_name='currentsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.song'),
        ),
        migrations.AddField(
            model_name='currentsong',
            name='virtual_environment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.virtualenvironment'),
        ),
    ]
