# Generated by Django 4.2.7 on 2024-07-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_currentsong_song_virtualenvironment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualenvironment',
            name='song',
        ),
    ]
